/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CaseStudyRouteImport } from './routes/case-study'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AftersalesRouteImport } from './routes/aftersales'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductIndexRouteImport } from './routes/product/index'
import { Route as ProductWetMixMacadamRouteImport } from './routes/product/wet-mix-macadam'
import { Route as ProductMechanicalHydraulicBroomerRouteImport } from './routes/product/mechanical-hydraulic-broomer'
import { Route as ProductHotMixRouteImport } from './routes/product/hot-mix'
import { Route as ProductDrumMixRouteImport } from './routes/product/drum-mix'
import { Route as ProductBitumenPressureDistributorRouteImport } from './routes/product/bitumen-pressure-distributor'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudyRoute = CaseStudyRouteImport.update({
  id: '/case-study',
  path: '/case-study',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AftersalesRoute = AftersalesRouteImport.update({
  id: '/aftersales',
  path: '/aftersales',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIndexRoute = ProductIndexRouteImport.update({
  id: '/product/',
  path: '/product/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductWetMixMacadamRoute = ProductWetMixMacadamRouteImport.update({
  id: '/product/wet-mix-macadam',
  path: '/product/wet-mix-macadam',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductMechanicalHydraulicBroomerRoute =
  ProductMechanicalHydraulicBroomerRouteImport.update({
    id: '/product/mechanical-hydraulic-broomer',
    path: '/product/mechanical-hydraulic-broomer',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductHotMixRoute = ProductHotMixRouteImport.update({
  id: '/product/hot-mix',
  path: '/product/hot-mix',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductDrumMixRoute = ProductDrumMixRouteImport.update({
  id: '/product/drum-mix',
  path: '/product/drum-mix',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductBitumenPressureDistributorRoute =
  ProductBitumenPressureDistributorRouteImport.update({
    id: '/product/bitumen-pressure-distributor',
    path: '/product/bitumen-pressure-distributor',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/aftersales': typeof AftersalesRoute
  '/careers': typeof CareersRoute
  '/case-study': typeof CaseStudyRoute
  '/contact': typeof ContactRoute
  '/product/bitumen-pressure-distributor': typeof ProductBitumenPressureDistributorRoute
  '/product/drum-mix': typeof ProductDrumMixRoute
  '/product/hot-mix': typeof ProductHotMixRoute
  '/product/mechanical-hydraulic-broomer': typeof ProductMechanicalHydraulicBroomerRoute
  '/product/wet-mix-macadam': typeof ProductWetMixMacadamRoute
  '/product': typeof ProductIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/aftersales': typeof AftersalesRoute
  '/careers': typeof CareersRoute
  '/case-study': typeof CaseStudyRoute
  '/contact': typeof ContactRoute
  '/product/bitumen-pressure-distributor': typeof ProductBitumenPressureDistributorRoute
  '/product/drum-mix': typeof ProductDrumMixRoute
  '/product/hot-mix': typeof ProductHotMixRoute
  '/product/mechanical-hydraulic-broomer': typeof ProductMechanicalHydraulicBroomerRoute
  '/product/wet-mix-macadam': typeof ProductWetMixMacadamRoute
  '/product': typeof ProductIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/aftersales': typeof AftersalesRoute
  '/careers': typeof CareersRoute
  '/case-study': typeof CaseStudyRoute
  '/contact': typeof ContactRoute
  '/product/bitumen-pressure-distributor': typeof ProductBitumenPressureDistributorRoute
  '/product/drum-mix': typeof ProductDrumMixRoute
  '/product/hot-mix': typeof ProductHotMixRoute
  '/product/mechanical-hydraulic-broomer': typeof ProductMechanicalHydraulicBroomerRoute
  '/product/wet-mix-macadam': typeof ProductWetMixMacadamRoute
  '/product/': typeof ProductIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/aftersales'
    | '/careers'
    | '/case-study'
    | '/contact'
    | '/product/bitumen-pressure-distributor'
    | '/product/drum-mix'
    | '/product/hot-mix'
    | '/product/mechanical-hydraulic-broomer'
    | '/product/wet-mix-macadam'
    | '/product'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/aftersales'
    | '/careers'
    | '/case-study'
    | '/contact'
    | '/product/bitumen-pressure-distributor'
    | '/product/drum-mix'
    | '/product/hot-mix'
    | '/product/mechanical-hydraulic-broomer'
    | '/product/wet-mix-macadam'
    | '/product'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/aftersales'
    | '/careers'
    | '/case-study'
    | '/contact'
    | '/product/bitumen-pressure-distributor'
    | '/product/drum-mix'
    | '/product/hot-mix'
    | '/product/mechanical-hydraulic-broomer'
    | '/product/wet-mix-macadam'
    | '/product/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AftersalesRoute: typeof AftersalesRoute
  CareersRoute: typeof CareersRoute
  CaseStudyRoute: typeof CaseStudyRoute
  ContactRoute: typeof ContactRoute
  ProductBitumenPressureDistributorRoute: typeof ProductBitumenPressureDistributorRoute
  ProductDrumMixRoute: typeof ProductDrumMixRoute
  ProductHotMixRoute: typeof ProductHotMixRoute
  ProductMechanicalHydraulicBroomerRoute: typeof ProductMechanicalHydraulicBroomerRoute
  ProductWetMixMacadamRoute: typeof ProductWetMixMacadamRoute
  ProductIndexRoute: typeof ProductIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-study': {
      id: '/case-study'
      path: '/case-study'
      fullPath: '/case-study'
      preLoaderRoute: typeof CaseStudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aftersales': {
      id: '/aftersales'
      path: '/aftersales'
      fullPath: '/aftersales'
      preLoaderRoute: typeof AftersalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/': {
      id: '/product/'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/wet-mix-macadam': {
      id: '/product/wet-mix-macadam'
      path: '/product/wet-mix-macadam'
      fullPath: '/product/wet-mix-macadam'
      preLoaderRoute: typeof ProductWetMixMacadamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/mechanical-hydraulic-broomer': {
      id: '/product/mechanical-hydraulic-broomer'
      path: '/product/mechanical-hydraulic-broomer'
      fullPath: '/product/mechanical-hydraulic-broomer'
      preLoaderRoute: typeof ProductMechanicalHydraulicBroomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/hot-mix': {
      id: '/product/hot-mix'
      path: '/product/hot-mix'
      fullPath: '/product/hot-mix'
      preLoaderRoute: typeof ProductHotMixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/drum-mix': {
      id: '/product/drum-mix'
      path: '/product/drum-mix'
      fullPath: '/product/drum-mix'
      preLoaderRoute: typeof ProductDrumMixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/bitumen-pressure-distributor': {
      id: '/product/bitumen-pressure-distributor'
      path: '/product/bitumen-pressure-distributor'
      fullPath: '/product/bitumen-pressure-distributor'
      preLoaderRoute: typeof ProductBitumenPressureDistributorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AftersalesRoute: AftersalesRoute,
  CareersRoute: CareersRoute,
  CaseStudyRoute: CaseStudyRoute,
  ContactRoute: ContactRoute,
  ProductBitumenPressureDistributorRoute:
    ProductBitumenPressureDistributorRoute,
  ProductDrumMixRoute: ProductDrumMixRoute,
  ProductHotMixRoute: ProductHotMixRoute,
  ProductMechanicalHydraulicBroomerRoute:
    ProductMechanicalHydraulicBroomerRoute,
  ProductWetMixMacadamRoute: ProductWetMixMacadamRoute,
  ProductIndexRoute: ProductIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
